version: 2
updates:
  # Enable version updates for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "tsilva"
    commit-message:
      prefix: "deps"
      include: "scope"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    assignees:
      - "tsilva"
    commit-message:
      prefix: "ci"
      include: "scope"
