name: Build and Publish to PyPI

on:
  push:
    branches:
      - main  # or 'master', or tag-based trigger like 'tags: v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for trusted publishing (optional)
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or your version

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}